services:
  postgres:
    image: "postgres:latest"
    volumes: 
      - "./data/pgsql:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: es
    volumes:
      - "./data/elasticsearch:/var/data/elasticsearch"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
    depends_on:
      - postgres
      - elasticsearch
networks:
  elastic:
    driver: bridge
